
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';

import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.css';
import './globals.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'ProjectSubmission',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Navigation />
          
          <div>
            {children}
          </div>
          <Footer />
        </div>

      </body>
    </html>
  )
}
